export enum AJVSchemaEnum {
  CompareCertReq = 'CompareCertReq',
  RepairOOSAccountsReq = 'RepairOOSAccountsReq',
  RequestStateForTxReq = 'RequestStateForTxReq',
  RequestStateForTxResp = 'RequestStateForTxResp',
  RequestReceiptForTxReq = 'RequestReceiptForTxReq',
  RequestReceiptForTxResp = 'RequestReceiptForTxResp',
  GetAppliedVoteReq = 'GetAppliedVoteReq',
  GetAppliedVoteResp = 'GetAppliedVoteResp',
  LostReportReq = 'LostReportReq',
  RequestStateForTxPostReq = 'RequestStateForTxPostReq',
  RequestStateForTxPostResp = 'RequestStateForTxPostResp',
  WrappedDataResponse = 'WrappedDataResponse',
  BroadcastStateReq = 'BroadcastStateReq',
  GetAccountDataReq = 'GetAccountDataReq',
  GetAccountDataResp = 'GetAccountDataResp',
  ApoptosisProposalReq = 'ApoptosisProposalReq',
  ApoptosisProposalResp = 'ApoptosisProposalResp',
  GetCachedAppDataReq = 'GetCachedAppDataReq',
  GetCachedAppDataResp = 'GetCachedAppDataResp',
  GetAccountDataByListReq = 'GetAccountDataByListReq',
  GetAccountDataByListResp = 'GetAccountDataByListResp',
}
