export enum TypeIdentifierEnum {
  cApoptosisProposalReq = 1,
  cApoptosisProposalResp,
  cWrappedReq,
  cWrappedResp,
  cWrappedDataResponse,
  cWrappedData,
  cBroadcastStateReq,
  cSendCachedAppDataReq,
  cCachedAppData,
  cGetAccountDataWithQueueHintsReq,
  cGetAccountDataWithQueueHintsResp,
  cWrappedDataFromQueue,
  cGetAccountQueueCountReq,
  cGetAccountQueueCountResp,
  cGetAccountDataByListReq,
  cGetAccountDataByListResp,
  cBroadcastFinalStateReq,
  cGetAccountData3Req,
  cGetAccountData3Resp,
}
