export enum TypeIdentifierEnum {
  cApoptosisProposalReq = 1,
  cApoptosisProposalResp,
  cWrappedReq,
  cWrappedResp,
  cWrappedDataResponse,
  cWrappedData,
  cBroadcastStateReq,
  cSendCachedAppDataReq,
  cCachedAppData,
  cGetAccountDataWithQueueHintsReq,
  cGetAccountDataWithQueueHintsResp,
  cWrappedDataFromQueue,
  cGetAccountQueueCountReq,
  cGetAccountQueueCountResp,
  cGetAccountDataByListReq,
  cGetAccountDataByListResp,
  cBroadcastFinalStateReq,
  cGetAccountDataReq,
  cGetAccountDataResp,
  cSyncTrieHashesReq,
  cCompareCertReq,
  cCompareCertResp,
  cGetTxTimestampReq,
  cGetTxTimestampResp,
  cGetTrieHashesReq,
  cGetTrieHashesResp,
}
